/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.gui;

import student.dbutil.DBConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author misha
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    public OptionsFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jrbAddEmp = new javax.swing.JRadioButton();
        jrbSearchEmp = new javax.swing.JRadioButton();
        jrbShowAllEmp = new javax.swing.JRadioButton();
        jrbDeleteEmp = new javax.swing.JRadioButton();
        jrbUpdateEmp = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Select Your Choice");

        jrbAddEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbAddEmp.setForeground(new java.awt.Color(51, 51, 51));
        jrbAddEmp.setText("Add Student");
        jrbAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAddEmpActionPerformed(evt);
            }
        });

        jrbSearchEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbSearchEmp.setForeground(new java.awt.Color(51, 51, 51));
        jrbSearchEmp.setText("Search Student");

        jrbShowAllEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbShowAllEmp.setForeground(new java.awt.Color(51, 51, 51));
        jrbShowAllEmp.setText("Show All  Student");

        jrbDeleteEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbDeleteEmp.setForeground(new java.awt.Color(51, 51, 51));
        jrbDeleteEmp.setText("Delete Student");

        jrbUpdateEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbUpdateEmp.setForeground(new java.awt.Color(51, 51, 51));
        jrbUpdateEmp.setText("Update Student");
        jrbUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUpdateEmpActionPerformed(evt);
            }
        });

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton6.setText("Quit");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(204, 204, 255));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jrbUpdateEmp)
                            .addComponent(jrbDeleteEmp)
                            .addComponent(jrbShowAllEmp)
                            .addComponent(jrbSearchEmp)
                            .addComponent(jrbAddEmp)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnDoTask)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(jrbAddEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbSearchEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbShowAllEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbDeleteEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbUpdateEmp)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton6)
                .addGap(27, 27, 27)
                .addComponent(btnDoTask)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAddEmpActionPerformed

    private void jrbUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUpdateEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbUpdateEmpActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
         // TODO add your handling code here:
         
           boolean result=validateInputs();
           if(!result){
               JOptionPane.showMessageDialog(null,"Please select an action first"); 
               return;
           }
           JFrame jf=null;
           if(jrbAddEmp.isSelected()){
               jf=new AddStudentFrame();           
           }
           else if(jrbShowAllEmp.isSelected()){
               jf=new ViewAllStudentsFrame();
           }
           else if(jrbSearchEmp.isSelected()){
               jf=new SearchStudentFrame();
           }
           else if(jrbDeleteEmp.isSelected()){
                jf=new RemoveStudentFrame();
           }
           else if(jrbUpdateEmp.isSelected()){
               jf=new UpdateStudentFrame();
           }
           else {
               DBConnection.closeConnection();
               System.exit(0);
           }
           jf.setVisible(true);;
           this.dispose();
    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jrbAddEmp;
    private javax.swing.JRadioButton jrbDeleteEmp;
    private javax.swing.JRadioButton jrbSearchEmp;
    private javax.swing.JRadioButton jrbShowAllEmp;
    private javax.swing.JRadioButton jrbUpdateEmp;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputs() {
     
        if(jrbUpdateEmp.isSelected()==false&& jrbDeleteEmp.isSelected()==false && jrbAddEmp.isSelected()==false && jrbShowAllEmp.isSelected()==false && jrbSearchEmp.isSelected()==false && jRadioButton6.isSelected()==false )
            return false;  
       return true;
    }
}
